// Code generated by Kitex v0.3.1. DO NOT EDIT.

package relationservice

import (
	"context"
	"github.com/bdyc-org/dousheng/kitex_gen/relation"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	QueryFollow(ctx context.Context, req *relation.QueryFollowRequest, callOptions ...callopt.Option) (r *relation.QueryFollowResponse, err error)
	QueryFollower(ctx context.Context, req *relation.QueryFollowerRequest, callOptions ...callopt.Option) (r *relation.QueryFollowerResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRelationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRelationServiceClient struct {
	*kClient
}

func (p *kRelationServiceClient) QueryFollow(ctx context.Context, req *relation.QueryFollowRequest, callOptions ...callopt.Option) (r *relation.QueryFollowResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryFollow(ctx, req)
}

func (p *kRelationServiceClient) QueryFollower(ctx context.Context, req *relation.QueryFollowerRequest, callOptions ...callopt.Option) (r *relation.QueryFollowerResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryFollower(ctx, req)
}
